# Generated by Django 2.2.28 on 2025-12-15 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20251215_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 15, 22, 25, 56, 179630), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='cardsproduct',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 15, 22, 25, 56, 179630), verbose_name='Дата комментария'),
        ),
    ]
