# Generated by Django 2.2.28 on 2025-12-16 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20251215_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 16, 22, 0, 24, 592662), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='cardsproduct',
            name='category',
            field=models.CharField(choices=[('photo_sessions', 'Фотосессии'), ('printed_products', 'Печатная продукция'), ('service_packages', 'Пакеты услуг')], default='photo_sessions', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 16, 22, 0, 24, 592662), verbose_name='Дата комментария'),
        ),
    ]
