# Generated by Django 2.2.28 on 2025-12-20 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20251219_1828'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='app_order_order_n_9a87c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='app_order_status_ffcc5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='app_order_user_id_eb2002_idx',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 20, 10, 32, 46, 95935), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 20, 10, 32, 46, 95935), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 20, 10, 32, 46, 96935), verbose_name='Дата заказа'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
