# Generated by Django 2.2.28 on 2025-12-20 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20251220_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 20, 12, 27, 47, 657703), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 20, 12, 27, 47, 657703), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 20, 12, 27, 47, 658703), verbose_name='Дата заказа'),
        ),
        migrations.AlterModelTable(
            name='ordercomment',
            table='OrderComments',
        ),
    ]
