# Generated by Django 2.2.28 on 2025-12-21 08:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20251220_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ordercomment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ordercomment',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='ordercomment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 21, 11, 14, 47, 757887), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 21, 11, 14, 47, 757887), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 21, 11, 14, 47, 758887), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Order'),
        ),
        migrations.AlterModelTable(
            name='ordercomment',
            table=None,
        ),
    ]
