# Generated by Django 2.2.28 on 2025-12-23 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20251222_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'Статья новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 18, 57, 16, 193805), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 18, 57, 16, 193805), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 18, 57, 16, 194811), verbose_name='Дата заказа'),
        ),
    ]
