# Generated by Django 2.2.28 on 2025-12-23 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20251223_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsproduct',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория (новая)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 32, 10, 36022), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 32, 10, 36527), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 32, 10, 37529), verbose_name='Дата заказа'),
        ),
    ]
