# Generated by Django 2.2.28 on 2025-12-23 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20251223_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsproduct',
            name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 41, 4, 211812), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 41, 4, 212810), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 41, 4, 213810), verbose_name='Дата заказа'),
        ),
    ]
