# Generated by Django 2.2.28 on 2025-12-23 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20251223_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsproduct',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 46, 24, 476489), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 46, 24, 476489), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 12, 23, 19, 46, 24, 477489), verbose_name='Дата заказа'),
        ),
    ]
